# Change these first
owner: glembin # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: 💼 GLEMBIN™ Brand & Infrastructure
    url: https://glembindd.pl/
  - name: 📚 GLEMBIN™ Edu - Ekstrakorki.pl (Educational Portal)
    url: https://ekstrakorki.pl/
  - name: 📚 GLEMBIN™ Edu - Personal Education Platform
    url: https://korki.nglembin.pl/
  - name: 🧩 Project under GLEMBIN™ - Responsive Web Development Service
    url: https://strony.nglembindd.pl/
  - name: 🧪 Personal Infrastructure & Testbed
    url: https://nglembin.pl/
  - name: 📈 Status Site
    url: https://statusdd.nglembin.pl/    

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.glembin.pl
  #baseUrl: /status
  logoUrl: https://glembin.pl/assets/img/glembinfavicon.png?h=75bebb116da98123a3309478158be0ee
  icon: https://glembin.pl/assets/img/glembinfavicon.png?h=75bebb116da98123a3309478158be0ee
  name: GLEMBIN™ Status
  introTitle: "**GLEMBIN™ Status** – real-time monitoring across the entire GLEMBIN ecosystem."
  introMessage: This page displays the current operational status of all **GLEMBIN services**, including **core infrastructure**, **public websites**, **internal tools**, and **automation bots** – monitored continuously to ensure stability and performance.
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://glembin.pl/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
