# Change these first
owner: nglembin # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Ekstrakorki
    url: https://ekstrakorki.pl/
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.glembin.com
  baseUrl: /status
  logoUrl: assets/glembinicon.png
  name: GLEMBIN™ Status
  introTitle: "**GLEMBIN™ Status** – the official uptime monitoring system for all GLEMBIN™ services."
  introMessage: This page displays the **current operational status** of key services in the GLEMBIN™ ecosystem, including websites, tools, and platforms. All systems are monitored continuously to ensure maximum reliability and performance.
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://glembin.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
