# Change these first
owner: glembin # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: 💼 GLEMBIN™ Business - glembin.pl/glembin.com
    url: https://glembin.pl/
  - name: 📚 GLEMBIN™ Edu - Ekstrakorki.pl
    url: https://ekstrakorki.pl/
  - name: 📚 GLEMBIN™ Edu - Personal Education Platform
    url: https://korki.nglembin.pl/
  - name: 🧪 Personal site
    url: https://nglembin.pl/
  - name: 📈 Status Site
    url: https://status.glembin.pl/

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.glembin.pl
  #baseUrl: /status
  logoUrl: https://glembin.pl/assets/img/glembinfavicon.png?h=75bebb116da98123a3309478158be0ee
  icon: https://glembin.pl/assets/img/glembinfavicon.png?h=75bebb116da98123a3309478158be0ee
  name: GLEMBIN™ Status
  introTitle: "**GLEMBIN Website Status**"
  introMessage: Check the real-time status of GLEMBIN websites, scheduled maintenance, and any ongoing incidents.
  navbar:
    - title: Status
      href: /
    - title: GLEMBIN
      href: https://glembin.pl/
    - title: Ekstrakorki
      href: https://ekstrakorki.pl/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
