# Change these first
owner: nglembin # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: 🔹GLEMBIN™ Brand & Infrastructure
    url: https://glembin.pl/
  - name: 🔸 Project under GLEMBIN™ - Ekstrakorki.pl
    url: https://ekstrakorki.pl/
  - name: 🔸 Project under GLEMBIN™ - korki.nglembin.pl
    url: https://korki.nglembin.pl/
  - name: 🔸 Project under GLEMBIN™ - strony.nglembin.pl
    url: https://strony.nglembin.pl/
  - name: ⚫ Personal Infrastructure
    url: https://nglembin.pl/

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.glembin.pl
  #baseUrl: /status
  logoUrl: https://glembin.pl/assets/img/glembinfavicon.png?h=75bebb116da98123a3309478158be0ee
  icon: https://glembin.pl/assets/img/glembinfavicon.png?h=75bebb116da98123a3309478158be0ee
  name: GLEMBIN™ Status
  introTitle: "**GLEMBIN™ Status** – the official uptime monitoring system for all GLEMBIN™ services."
  introMessage: This page displays the **current operational status** of key services in the GLEMBIN™ ecosystem, including websites, tools, and platforms. All systems are monitored continuously to ensure maximum reliability and performance.

  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://glembin.pl/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
